require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '9.0'

target 'SeaOfFish' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativePayments', :path => '../node_modules/react-native-payments'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'


  pod 'RNYamap', :path => '../node_modules/react-native-yamap'

  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-rn-apple-pay-button', :path => '../node_modules/react-native-rn-apple-pay-button'

  pod 'RNTinkoffAsdk', :path => '../node_modules/react-native-tinkoff-asdk'

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'SeaOfFishTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'SeaOfFish-tvOS' do
  # Pods for SeaOfFish-tvOS

  target 'SeaOfFish-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
